on:
  release:
    types: [published]

jobs:
  download_rename_publish:
    runs-on: codeberg-tiny-lazy
    container:
      image: node:20-alpine
    steps:
      - name: install zip
        run: apk add --no-cache zip git
      - uses: actions/checkout@v4
      - name: create kwinscript package
        run: |
          zip -r fluid-tile-${{github.ref_name}}.kwinscript metadata.json contents/
          mkdir build
          mv ./fluid-tile-${{github.ref_name}}.kwinscript ./build
      - name: upload kwinscript
        uses: actions/forgejo-release@v2.7.3
        with:
          direction: upload
          release-dir: build
